spring:
  application:
    name: bank-api

  data:
    mongodb:
      port: 27017
      database: bank-oidc
      host: localhost


  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

server:
  port: 6001




